// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MySecureWebApi.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MySecureWebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250724172406_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MySecureWebApi.Models.Officer", b =>
                {
                    b.Property<int>("OfficerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("officer_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OfficerId"));

                    b.Property<string>("OfficerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("officer_name");

                    b.Property<string>("Rank")
                        .HasColumnType("text")
                        .HasColumnName("officer_rank");

                    b.HasKey("OfficerId");

                    b.ToTable("officers");
                });

            modelBuilder.Entity("MySecureWebApi.Models.Rank", b =>
                {
                    b.Property<int>("RankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rank_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RankId"));

                    b.Property<string>("RankName")
                        .HasColumnType("text")
                        .HasColumnName("rank_name");

                    b.HasKey("RankId");

                    b.ToTable("ranks");
                });

            modelBuilder.Entity("MySecureWebApi.Models.Ship", b =>
                {
                    b.Property<int>("ShipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ship_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShipId"));

                    b.Property<string>("Registry")
                        .HasColumnType("text")
                        .HasColumnName("registry");

                    b.Property<string>("ShipName")
                        .HasColumnType("text")
                        .HasColumnName("ship_name");

                    b.HasKey("ShipId");

                    b.ToTable("ships");
                });
#pragma warning restore 612, 618
        }
    }
}
